version: "3.9"

services:

  nginx:
    image: nginx:1.29.5
    container_name: opencart_nginx
    depends_on:
      - php
    ports:
      - "8080:8080"
    volumes:
      - opencart_www:/var/www
      - ./opencart.conf:/etc/nginx/conf.d/default.conf:ro,Z
    restart: unless-stopped

  php:
    build: .
    container_name: opencart
    depends_on:
      - db
    expose:
      - "9000"
    volumes:
      - opencart_www:/var/www
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: opencart
      MARIADB_USER: opencart
      MARIADB_PASSWORD: opencartpass
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  opencart_www:
  mariadb_data:
